export { default as DashboardPage } from './Dashboard'
export { default as CardsPage } from './Cards'
export { default as LandingPage } from './Landing'
export { default as FaqsPage } from './Faqs'
export { default as ContactUsPage } from './ContactUs'
export { default as Page404 } from './404'
